set(ABSE_ANDROID_PREBUILT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../prebuilt/${ANDROID_ABI}")

set(ABSE_ANDROID_PREBUILT_INCLUDE_DIR "${ABSE_ANDROID_PREBUILT_ROOT}/include")
set(ABSE_ANDROID_PREBUILT_LIB_DIR "${ABSE_ANDROID_PREBUILT_ROOT}/lib")

message(STATUS "ABSE Android prebuilt root: ${ABSE_ANDROID_PREBUILT_ROOT}")

if(NOT EXISTS "${ABSE_ANDROID_PREBUILT_INCLUDE_DIR}")
  message(FATAL_ERROR
    "Missing Android prebuilt include directory for ABI ${ANDROID_ABI}: "
    "${ABSE_ANDROID_PREBUILT_INCLUDE_DIR}")
endif()

if(NOT EXISTS "${ABSE_ANDROID_PREBUILT_LIB_DIR}")
  message(FATAL_ERROR
    "Missing Android prebuilt lib directory for ABI ${ANDROID_ABI}: "
    "${ABSE_ANDROID_PREBUILT_LIB_DIR}")
endif()

add_library(oqs STATIC IMPORTED GLOBAL)
set_target_properties(oqs PROPERTIES
  IMPORTED_LOCATION "${ABSE_ANDROID_PREBUILT_LIB_DIR}/liboqs.a"
)

add_library(OPENFHEcore STATIC IMPORTED GLOBAL)
set_target_properties(OPENFHEcore PROPERTIES
  IMPORTED_LOCATION "${ABSE_ANDROID_PREBUILT_LIB_DIR}/libOPENFHEcore.a"
)

set(ABSE_ANDROID_PREBUILT_INCLUDE_DIRS
  "${ABSE_ANDROID_PREBUILT_INCLUDE_DIR}"
  "${ABSE_ANDROID_PREBUILT_INCLUDE_DIR}/openfhe"
  "${ABSE_ANDROID_PREBUILT_INCLUDE_DIR}/openfhe/core"
)
