#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <random>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "entities/SoftwareTee.h"
#include "system/Cli.h"
#include "system/RuntimePaths.h"

namespace {

using namespace abse_zkp;

struct SyntheticUser {
    std::string gid;
    int identity_secret = 0;
    std::vector<std::string> attributes;
};

struct SyntheticBundle {
    std::string label;
    std::string owner_gid;
    std::string plaintext;
    std::vector<std::string> keywords;
    std::vector<std::string> policy_attributes;
    std::string policy_expression;
    std::vector<std::string> authorized_gids;
};

std::string PadNumber(std::size_t value, int width = 4) {
    std::ostringstream out;
    out << std::setw(width) << std::setfill('0') << value;
    return out.str();
}

std::vector<int> ParseIntList(const std::string& value) {
    std::vector<int> values;
    if (value.empty()) {
        return values;
    }

    std::stringstream input(value);
    std::string item;
    while (std::getline(input, item, ',')) {
        if (!item.empty()) {
            values.push_back(std::stoi(item));
        }
    }
    return values;
}

template <typename T>
std::string JoinStrings(const std::vector<T>& values, const std::string& delimiter = ",") {
    std::ostringstream out;
    for (std::size_t i = 0; i < values.size(); ++i) {
        if (i > 0) {
            out << delimiter;
        }
        out << values[i];
    }
    return out.str();
}

template <typename T>
std::vector<T> SampleWithoutReplacement(const std::vector<T>& pool, std::size_t count, std::mt19937& rng) {
    if (count > pool.size()) {
        throw std::invalid_argument("sample size exceeds pool size");
    }

    std::vector<std::size_t> indices(pool.size());
    std::iota(indices.begin(), indices.end(), 0);
    std::shuffle(indices.begin(), indices.end(), rng);

    std::vector<T> sampled;
    sampled.reserve(count);
    for (std::size_t i = 0; i < count; ++i) {
        sampled.push_back(pool[indices[i]]);
    }
    std::sort(sampled.begin(), sampled.end());
    return sampled;
}

std::string MakePolicyExpression(const std::string& policy_type,
                                 const std::vector<std::string>& attributes,
                                 std::size_t threshold) {
    if (policy_type == "attribute") {
        if (attributes.size() != 1) {
            throw std::invalid_argument("attribute policy requires exactly one attribute");
        }
        return attributes.front();
    }
    if (policy_type == "and") {
        return "AND(" + JoinStrings(attributes) + ")";
    }
    if (policy_type == "or") {
        return "OR(" + JoinStrings(attributes) + ")";
    }
    if (policy_type == "threshold") {
        return "THRESHOLD(" + std::to_string(threshold) + "," + JoinStrings(attributes) + ")";
    }
    throw std::invalid_argument("unsupported policy type: " + policy_type);
}

std::vector<std::string> MakeKeywordPool(std::size_t count) {
    std::vector<std::string> pool;
    pool.reserve(count);
    for (std::size_t i = 1; i <= count; ++i) {
        pool.push_back("kw_" + PadNumber(i));
    }
    return pool;
}

std::vector<std::string> MakeAttributePool(std::size_t count) {
    std::vector<std::string> pool;
    pool.reserve(count);
    for (std::size_t i = 1; i <= count; ++i) {
        pool.push_back("attr_" + PadNumber(i));
    }
    return pool;
}

void WriteScenarioFile(const std::filesystem::path& output_path,
                       const std::vector<SyntheticUser>& users,
                       const std::vector<SyntheticBundle>& bundles,
                       const std::vector<int>& query_sizes,
                       int queries_per_size,
                       int revocation_count,
                       std::mt19937& rng) {
    std::filesystem::create_directories(output_path.parent_path());
    std::ofstream output(output_path, std::ios::trunc);
    if (!output.is_open()) {
        throw std::runtime_error("failed to open synthetic scenario output: " + output_path.string());
    }

    output << "# Synthetic benchmark scenario generated by generate_synthetic_scenario.\n";
    output << "# Users=" << users.size()
           << ", bundles=" << bundles.size()
           << ", query_sizes=" << JoinStrings(query_sizes)
           << ", queries_per_size=" << queries_per_size << "\n\n";

    for (const auto& user : users) {
        output << "user." << user.gid << ".identity_secret=" << user.identity_secret << '\n';
        output << "user." << user.gid << ".attributes=" << JoinStrings(user.attributes) << "\n\n";
    }

    for (const auto& bundle : bundles) {
        output << "bundle." << bundle.label << ".data_owner_gid=" << bundle.owner_gid << '\n';
        output << "bundle." << bundle.label << ".plaintext=" << bundle.plaintext << '\n';
        output << "bundle." << bundle.label << ".keywords=" << JoinStrings(bundle.keywords) << '\n';
        output << "bundle." << bundle.label << ".policy=" << bundle.policy_expression << "\n\n";
    }

    for (int query_size : query_sizes) {
        std::vector<std::size_t> eligible_bundles;
        for (std::size_t i = 0; i < bundles.size(); ++i) {
            if (static_cast<std::size_t>(query_size) <= bundles[i].keywords.size() &&
                !bundles[i].authorized_gids.empty()) {
                eligible_bundles.push_back(i);
            }
        }
        if (eligible_bundles.empty()) {
            throw std::runtime_error("no eligible bundles available for query size " + std::to_string(query_size));
        }

        std::uniform_int_distribution<std::size_t> bundle_distribution(0, eligible_bundles.size() - 1);
        for (int q = 1; q <= queries_per_size; ++q) {
            const auto& bundle = bundles[eligible_bundles[bundle_distribution(rng)]];
            const auto query_keywords =
                SampleWithoutReplacement(bundle.keywords, static_cast<std::size_t>(query_size), rng);
            std::uniform_int_distribution<std::size_t> user_distribution(0, bundle.authorized_gids.size() - 1);
            const std::string query_name = "q" + std::to_string(query_size) + "_" + std::to_string(q);
            output << "query." << query_name << ".gid=" << bundle.authorized_gids[user_distribution(rng)] << '\n';
            output << "query." << query_name << ".bundle_label=" << bundle.label << '\n';
            output << "query." << query_name << ".keywords=" << JoinStrings(query_keywords) << "\n\n";
        }
    }

    for (int i = 0; i < revocation_count && i < static_cast<int>(users.size()); ++i) {
        output << "revocation.revoke_" << users[static_cast<std::size_t>(i)].gid
               << ".gid=" << users[static_cast<std::size_t>(i)].gid << '\n';
    }
}

}  // namespace

int main(int argc, char** argv) {
    using namespace abse_zkp;
    CliArgs cli(argc, argv);

    const int user_count = std::stoi(cli.Get("--users", "20"));
    const int bundle_count = std::stoi(cli.Get("--bundles", "100"));
    const int keyword_pool_count = std::stoi(cli.Get("--keyword-pool", "200"));
    const int keywords_per_bundle = std::stoi(cli.Get("--keywords-per-bundle", "50"));
    const int attribute_pool_count = std::stoi(cli.Get("--attribute-pool", "50"));
    const int attributes_per_user = std::stoi(cli.Get("--attrs-per-user", "20"));
    const int attributes_per_policy = std::stoi(cli.Get("--attrs-per-policy", "10"));
    const auto query_sizes = ParseIntList(cli.Get("--query-sizes", "10,20,50"));
    const int queries_per_size = std::stoi(cli.Get("--queries-per-size", "3"));
    const int revocation_count = std::stoi(cli.Get("--revocations", "3"));
    const std::string policy_type = cli.Get("--policy-type", "and");
    const auto seed = static_cast<std::mt19937::result_type>(std::stoul(cli.Get("--seed", "1337")));
    const auto output_path =
        std::filesystem::path(cli.Get("--output", (WorkspaceRoot() / "config" / "synthetic_benchmark.conf").string()));

    if (user_count <= 0 || bundle_count <= 0 || keyword_pool_count <= 0 || attribute_pool_count <= 0 ||
        keywords_per_bundle <= 0 || attributes_per_user <= 0 || attributes_per_policy <= 0 ||
        queries_per_size <= 0 || revocation_count < 0) {
        throw std::invalid_argument("all count parameters must be positive, except revocations which may be zero");
    }
    if (keywords_per_bundle > keyword_pool_count) {
        throw std::invalid_argument("keywords-per-bundle cannot exceed keyword-pool");
    }
    if (attributes_per_user > attribute_pool_count) {
        throw std::invalid_argument("attrs-per-user cannot exceed attribute-pool");
    }
    if (attributes_per_policy > attributes_per_user) {
        throw std::invalid_argument("attrs-per-policy cannot exceed attrs-per-user");
    }
    if (query_sizes.empty()) {
        throw std::invalid_argument("query-sizes must contain at least one value");
    }
    const int max_query_size = *std::max_element(query_sizes.begin(), query_sizes.end());
    if (max_query_size > keywords_per_bundle) {
        throw std::invalid_argument("max query size cannot exceed keywords-per-bundle in exact-match benchmark mode");
    }

    std::size_t threshold = static_cast<std::size_t>(std::stoul(cli.Get(
        "--threshold",
        std::to_string(std::max(1, std::min(attributes_per_policy, std::max(1, attributes_per_policy / 2)))))));
    if (policy_type == "attribute") {
        threshold = 1;
    }
    if (policy_type == "threshold" && (threshold == 0 || threshold > static_cast<std::size_t>(attributes_per_policy))) {
        throw std::invalid_argument("threshold must be within attrs-per-policy");
    }

    std::mt19937 rng(seed);
    const auto keyword_pool = MakeKeywordPool(static_cast<std::size_t>(keyword_pool_count));
    const auto attribute_pool = MakeAttributePool(static_cast<std::size_t>(attribute_pool_count));

    std::vector<SyntheticUser> users;
    users.reserve(static_cast<std::size_t>(user_count));
    for (int i = 1; i <= user_count; ++i) {
        SyntheticUser user;
        user.gid = "user_" + PadNumber(static_cast<std::size_t>(i));
        user.identity_secret = 1000 + i;
        user.attributes = SampleWithoutReplacement(attribute_pool, static_cast<std::size_t>(attributes_per_user), rng);
        users.push_back(std::move(user));
    }

    std::vector<SyntheticBundle> bundles;
    bundles.reserve(static_cast<std::size_t>(bundle_count));
    for (int i = 1; i <= bundle_count; ++i) {
        SyntheticBundle bundle;
        const auto& owner = users[static_cast<std::size_t>((i - 1) % user_count)];
        bundle.label = "bundle_" + PadNumber(static_cast<std::size_t>(i));
        bundle.owner_gid = owner.gid;
        bundle.plaintext = "synthetic_plaintext_" + std::to_string(i);
        bundle.keywords =
            SampleWithoutReplacement(keyword_pool, static_cast<std::size_t>(keywords_per_bundle), rng);
        bundle.policy_attributes =
            SampleWithoutReplacement(owner.attributes, static_cast<std::size_t>(attributes_per_policy), rng);
        bundle.policy_expression = MakePolicyExpression(policy_type, bundle.policy_attributes, threshold);
        const auto logical_policy = BuildLogicalPolicyFromParts(policy_type, bundle.policy_attributes, threshold);
        for (const auto& user : users) {
            if (PolicySatisfied(user.attributes, logical_policy)) {
                bundle.authorized_gids.push_back(user.gid);
            }
        }
        if (bundle.authorized_gids.empty()) {
            bundle.authorized_gids.push_back(owner.gid);
        }
        bundles.push_back(std::move(bundle));
    }

    WriteScenarioFile(output_path, users, bundles, query_sizes, queries_per_size, revocation_count, rng);

    std::cout << "Synthetic scenario written to " << output_path << '\n';
    std::cout << "Users: " << users.size()
              << ", bundles: " << bundles.size()
              << ", keyword pool: " << keyword_pool.size()
              << ", attributes: " << attribute_pool.size() << '\n';
    std::cout << "Keywords per bundle: " << keywords_per_bundle
              << ", attrs per user: " << attributes_per_user
              << ", attrs per policy: " << attributes_per_policy << '\n';
    std::cout << "Query sizes: " << JoinStrings(query_sizes)
              << ", queries per size: " << queries_per_size
              << ", revocations: " << revocation_count << '\n';
    return 0;
}
